FILESEXTRAPATHS:prepend:stm32mpcommon := "${THISDIR}/${PN}:"

do_install:append:stm32mposscommon () {
    install -d ${D}${sysconfdir}/default

    echo "#Autogenerated" > ${D}${sysconfdir}/default/weston
    echo "#OPTARGS=--use-pixman" >> ${D}${sysconfdir}/default/weston
}
