FILESEXTRAPATHS_prepend_stm32mpcommon := "${THISDIR}/${PN}:"

do_install_append_stm32mposscommon () {
    install -d ${D}${sysconfdir}/default

    echo "#Autogenerated" > ${D}${sysconfdir}/default/weston
    echo "#OPTARGS=--use-pixman" >> ${D}${sysconfdir}/default/weston
}
